cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran -DENABLE_WARN_ELEV_DEBUG=ON -DENABLE_OUTPUT_NETCDF=ON -DCMAKE_Fortran_FLAGS="-g"


cmake .. -DBUILD_ADCIRC=ON -DBUILD_PADCIRC=ON -DBUILD_ADCPREP=ON -DBUILD_PADCSWAN=OFF
