export NETCDFHOME=$TACC_NETCDF_DIR
export TAU_OPTIONS='-optRevert'

cmake .. -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DCMAKE_Fortran_COMPILER=ifort -DENABLE_WARN_ELEV_DEBUG=ON -DCMAKE_Fortran_FLAGS='-xHost'

cmake .. -DBUILD_ADCIRC=ON -DBUILD_PADCIRC=ON -DBUILD_ADCPREP=ON -DBUILD_PADCSWAN=OFF -DENABLE_OUTPUT_NETCDF=ON
