#!/usr/bin/env sh

cmake .. -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DCMAKE_Fortran_COMPILER=ifx -DENABLE_WARN_ELEV_DEBUG=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_Fortran_FLAGS='-O0 -g -traceback '

cmake .. -DBUILD_ADCIRC=ON -DBUILD_PADCIRC=ON -DBUILD_ADCPREP=ON -DBUILD_PADCSWAN=OFF -DENABLE_OUTPUT_NETCDF=ON
