export NETCDFHOME=$TACC_NETCDF_DIR
export TAU_OPTIONS='-optRevert'

cmake .. -DCMAKE_C_COMPILER=tau_cc.sh -DCMAKE_CXX_COMPILER=tau_cxx.sh -DCMAKE_Fortran_COMPILER=tau_f90.sh -DENABLE_WARN_ELEV_DEBUG=ON -DCMAKE_Fortran_FLAGS='-xHost'

cmake .. -DBUILD_ADCIRC=ON -DBUILD_PADCIRC=ON -DBUILD_ADCPREP=ON -DBUILD_PADCSWAN=OFF -DENABLE_OUTPUT_NETCDF=ON
